### ISSUE TITLE
How to use this with HMVC in CI3

### ISSUE THREAD

**Issue by ranasoyab** [avramovic/DMLite-ORM#1]
How we can implement it with HMVC and CI3

**Comment by ranasoyab** [comment]
Ok got the answer.

As in Old Datamapper we do not load the model.
But as per your new version, we have to load model and then we can use.

So if possible try to auto load the model as when the object is created as old one :)

**Comment by avramovic** [comment]
So is this resolved or not?

To be honest, I'm a little bit busy with some other works so I'm not using CI3 at the moment and I never used it with HMVC. This library extends Model class, so if your models extend my model, it should work out of the box.

So just use `class Yourmodel extends MY_Model` instead of `class Yourmodel extends CI_Model`. Or is there something I'm missing here?

**Comment by ranasoyab** [comment]
No you are not missing.

But in old Data Mapper we have auto load model.

But as per your way.
Firstly we have to load model and then we can use it.

**Comment by avramovic** [comment]
I'm simply following the CI3 rules there. You should be able to list your models to be automatically loaded in `application/config/autoload.php`
